// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: room/room.proto

package room

import (
	common "github.com/Waylon1991/KingdomProto/common"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//玩家信息
type RoomPlayerChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  //玩家id
	Seat         int32               `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`                                    //玩家座位号
	Blood        int32               `protobuf:"varint,3,opt,name=blood,proto3" json:"blood,omitempty"`                                  //变化的血量数
	Cp           int32               `protobuf:"varint,4,opt,name=cp,proto3" json:"cp,omitempty"`                                        //变化的战斗点数
	ObtainCards  []*common.RoomCard  `protobuf:"bytes,5,rep,name=obtain_cards,json=obtainCards,proto3" json:"obtain_cards,omitempty"`    //获得的手牌列表
	LoseCards    []*common.RoomCard  `protobuf:"bytes,6,rep,name=lose_cards,json=loseCards,proto3" json:"lose_cards,omitempty"`          //失去的手牌列表
	ObtainBuffs  []*common.RoomBuf   `protobuf:"bytes,7,rep,name=obtain_buffs,json=obtainBuffs,proto3" json:"obtain_buffs,omitempty"`    //获得的buff列表
	LoseBuffs    []*common.RoomBuf   `protobuf:"bytes,8,rep,name=lose_buffs,json=loseBuffs,proto3" json:"lose_buffs,omitempty"`          //失去的buff列表
	ObtainSkills []*common.RoomSkill `protobuf:"bytes,9,rep,name=obtain_skills,json=obtainSkills,proto3" json:"obtain_skills,omitempty"` //获得的技能列表
	LoseSkills   []*common.RoomSkill `protobuf:"bytes,10,rep,name=lose_skills,json=loseSkills,proto3" json:"lose_skills,omitempty"`      //失去的技能列表
	LeftCard     int32               `protobuf:"varint,11,opt,name=left_card,json=leftCard,proto3" json:"left_card,omitempty"`           //剩余牌数
}

func (x *RoomPlayerChange) Reset() {
	*x = RoomPlayerChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerChange) ProtoMessage() {}

func (x *RoomPlayerChange) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerChange.ProtoReflect.Descriptor instead.
func (*RoomPlayerChange) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPlayerChange) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomPlayerChange) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *RoomPlayerChange) GetBlood() int32 {
	if x != nil {
		return x.Blood
	}
	return 0
}

func (x *RoomPlayerChange) GetCp() int32 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *RoomPlayerChange) GetObtainCards() []*common.RoomCard {
	if x != nil {
		return x.ObtainCards
	}
	return nil
}

func (x *RoomPlayerChange) GetLoseCards() []*common.RoomCard {
	if x != nil {
		return x.LoseCards
	}
	return nil
}

func (x *RoomPlayerChange) GetObtainBuffs() []*common.RoomBuf {
	if x != nil {
		return x.ObtainBuffs
	}
	return nil
}

func (x *RoomPlayerChange) GetLoseBuffs() []*common.RoomBuf {
	if x != nil {
		return x.LoseBuffs
	}
	return nil
}

func (x *RoomPlayerChange) GetObtainSkills() []*common.RoomSkill {
	if x != nil {
		return x.ObtainSkills
	}
	return nil
}

func (x *RoomPlayerChange) GetLoseSkills() []*common.RoomSkill {
	if x != nil {
		return x.LoseSkills
	}
	return nil
}

func (x *RoomPlayerChange) GetLeftCard() int32 {
	if x != nil {
		return x.LeftCard
	}
	return 0
}

//房间信息变化
type RoomInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players *RoomPlayerChange     `protobuf:"bytes,1,opt,name=players,proto3" json:"players,omitempty"` //玩家信息变化
	Ball    *common.RewardBall    `protobuf:"bytes,2,opt,name=ball,proto3" json:"ball,omitempty"`       //占卜球信息
	Record  *common.OperateRecord `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`   //操作记录信息
}

func (x *RoomInfoChange) Reset() {
	*x = RoomInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoChange) ProtoMessage() {}

func (x *RoomInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoChange.ProtoReflect.Descriptor instead.
func (*RoomInfoChange) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfoChange) GetPlayers() *RoomPlayerChange {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfoChange) GetBall() *common.RewardBall {
	if x != nil {
		return x.Ball
	}
	return nil
}

func (x *RoomInfoChange) GetRecord() *common.OperateRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

//新建房间
type NewRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode  common.RoomMode `protobuf:"varint,1,opt,name=mode,proto3,enum=protocol.common.RoomMode" json:"mode,omitempty"`                                                              //模式
	Infos map[int32]int32 `protobuf:"bytes,2,rep,name=Infos,proto3" json:"Infos,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //用户选择的英雄信息
}

func (x *NewRoomRequest) Reset() {
	*x = NewRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomRequest) ProtoMessage() {}

func (x *NewRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomRequest.ProtoReflect.Descriptor instead.
func (*NewRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *NewRoomRequest) GetMode() common.RoomMode {
	if x != nil {
		return x.Mode
	}
	return common.RoomMode(0)
}

func (x *NewRoomRequest) GetInfos() map[int32]int32 {
	if x != nil {
		return x.Infos
	}
	return nil
}

//房间信息
type NewRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInfo *common.RoomInfo `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` //房间信息
}

func (x *NewRoomReply) Reset() {
	*x = NewRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomReply) ProtoMessage() {}

func (x *NewRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomReply.ProtoReflect.Descriptor instead.
func (*NewRoomReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *NewRoomReply) GetRoomInfo() *common.RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

//请求房间信息
type RoomInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` //房间id
}

func (x *RoomInfoRequest) Reset() {
	*x = RoomInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoRequest) ProtoMessage() {}

func (x *RoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoRequest.ProtoReflect.Descriptor instead.
func (*RoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomInfoRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

//房间信息
type RoomInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInfo *common.RoomInfo `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` //房间信息
}

func (x *RoomInfoReply) Reset() {
	*x = RoomInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoReply) ProtoMessage() {}

func (x *RoomInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoReply.ProtoReflect.Descriptor instead.
func (*RoomInfoReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomInfoReply) GetRoomInfo() *common.RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

//请求使用buff
type UseBuffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuffId   int32   `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"`              // buff id
	ObjSeats []int32 `protobuf:"varint,2,rep,packed,name=obj_seats,json=objSeats,proto3" json:"obj_seats,omitempty"` //目标座位，不传就根据id来自动判断，如果判断不了会返回错误
	UserId   int32   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              //玩家id
}

func (x *UseBuffRequest) Reset() {
	*x = UseBuffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseBuffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseBuffRequest) ProtoMessage() {}

func (x *UseBuffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseBuffRequest.ProtoReflect.Descriptor instead.
func (*UseBuffRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{6}
}

func (x *UseBuffRequest) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *UseBuffRequest) GetObjSeats() []int32 {
	if x != nil {
		return x.ObjSeats
	}
	return nil
}

func (x *UseBuffRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

//返回使用buff(客户端是否需要？)
type UseBuffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suc    bool   `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"`      //是否成功
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` //原因
}

func (x *UseBuffReply) Reset() {
	*x = UseBuffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseBuffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseBuffReply) ProtoMessage() {}

func (x *UseBuffReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseBuffReply.ProtoReflect.Descriptor instead.
func (*UseBuffReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{7}
}

func (x *UseBuffReply) GetSuc() bool {
	if x != nil {
		return x.Suc
	}
	return false
}

func (x *UseBuffReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

//请求出牌
type OutCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuffId   int32   `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"`              // buff id
	ObjSeats []int32 `protobuf:"varint,2,rep,packed,name=obj_seats,json=objSeats,proto3" json:"obj_seats,omitempty"` //目标座位，不传就根据id来自动判断，如果判断不了会返回错误
	UserId   int32   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              //玩家id
}

func (x *OutCardRequest) Reset() {
	*x = OutCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardRequest) ProtoMessage() {}

func (x *OutCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardRequest.ProtoReflect.Descriptor instead.
func (*OutCardRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{8}
}

func (x *OutCardRequest) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *OutCardRequest) GetObjSeats() []int32 {
	if x != nil {
		return x.ObjSeats
	}
	return nil
}

func (x *OutCardRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

//返回打出卡牌(客户端是否需要？)
type OutCardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suc bool `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"` //是否成功
}

func (x *OutCardReply) Reset() {
	*x = OutCardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardReply) ProtoMessage() {}

func (x *OutCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardReply.ProtoReflect.Descriptor instead.
func (*OutCardReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{9}
}

func (x *OutCardReply) GetSuc() bool {
	if x != nil {
		return x.Suc
	}
	return false
}

//请求出售卡牌
type SellCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardIds []int32 `protobuf:"varint,1,rep,packed,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"` //出售卡牌列表
	UserId  int32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           //玩家id
}

func (x *SellCardRequest) Reset() {
	*x = SellCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellCardRequest) ProtoMessage() {}

func (x *SellCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellCardRequest.ProtoReflect.Descriptor instead.
func (*SellCardRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{10}
}

func (x *SellCardRequest) GetCardIds() []int32 {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *SellCardRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

//返回出售卡牌结果
type SellCardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suc bool `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"` //是否成功
}

func (x *SellCardReply) Reset() {
	*x = SellCardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellCardReply) ProtoMessage() {}

func (x *SellCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellCardReply.ProtoReflect.Descriptor instead.
func (*SellCardReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{11}
}

func (x *SellCardReply) GetSuc() bool {
	if x != nil {
		return x.Suc
	}
	return false
}

//使用技能
type UseSkillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UseSkillRequest) Reset() {
	*x = UseSkillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSkillRequest) ProtoMessage() {}

func (x *UseSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSkillRequest.ProtoReflect.Descriptor instead.
func (*UseSkillRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{12}
}

type UseSkillReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UseSkillReply) Reset() {
	*x = UseSkillReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseSkillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSkillReply) ProtoMessage() {}

func (x *UseSkillReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSkillReply.ProtoReflect.Descriptor instead.
func (*UseSkillReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{13}
}

type RollDiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollDiceRequest) Reset() {
	*x = RollDiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollDiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollDiceRequest) ProtoMessage() {}

func (x *RollDiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollDiceRequest.ProtoReflect.Descriptor instead.
func (*RollDiceRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{14}
}

type RollDiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollDiceReply) Reset() {
	*x = RollDiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollDiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollDiceReply) ProtoMessage() {}

func (x *RollDiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollDiceReply.ProtoReflect.Descriptor instead.
func (*RollDiceReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{15}
}

type GiveUpDiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GiveUpDiceRequest) Reset() {
	*x = GiveUpDiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveUpDiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveUpDiceRequest) ProtoMessage() {}

func (x *GiveUpDiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveUpDiceRequest.ProtoReflect.Descriptor instead.
func (*GiveUpDiceRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{16}
}

type GiveUpDiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GiveUpDiceReply) Reset() {
	*x = GiveUpDiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveUpDiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveUpDiceReply) ProtoMessage() {}

func (x *GiveUpDiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveUpDiceReply.ProtoReflect.Descriptor instead.
func (*GiveUpDiceReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{17}
}

type UseToolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UseToolRequest) Reset() {
	*x = UseToolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseToolRequest) ProtoMessage() {}

func (x *UseToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseToolRequest.ProtoReflect.Descriptor instead.
func (*UseToolRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{18}
}

type UseToolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UseToolReply) Reset() {
	*x = UseToolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseToolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseToolReply) ProtoMessage() {}

func (x *UseToolReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseToolReply.ProtoReflect.Descriptor instead.
func (*UseToolReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{19}
}

type SkipStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SkipStageRequest) Reset() {
	*x = SkipStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipStageRequest) ProtoMessage() {}

func (x *SkipStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipStageRequest.ProtoReflect.Descriptor instead.
func (*SkipStageRequest) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{20}
}

type SkipStageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SkipStageReply) Reset() {
	*x = SkipStageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_room_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipStageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipStageReply) ProtoMessage() {}

func (x *SkipStageReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipStageReply.ProtoReflect.Descriptor instead.
func (*SkipStageReply) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{21}
}

var File_room_room_proto protoreflect.FileDescriptor

var file_room_room_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee,
	0x03, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x63, 0x70, 0x12, 0x3c, 0x0a, 0x0c, 0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e,
	0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x09, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x3b,
	0x0a, 0x0c, 0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x75, 0x66, 0x52, 0x0b,
	0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x6c,
	0x6f, 0x73, 0x65, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x75, 0x66, 0x52, 0x09, 0x6c, 0x6f, 0x73, 0x65, 0x42,
	0x75, 0x66, 0x66, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x5f, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0c, 0x6f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0a, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22,
	0xb4, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a,
	0x04, 0x62, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x12, 0x36,
	0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x46, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x33, 0x0a, 0x0f, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x47, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x36, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5f, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x42,
	0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75,
	0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x66,
	0x66, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x53, 0x65, 0x61, 0x74, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x55, 0x73, 0x65,
	0x42, 0x75, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x75, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x5f, 0x0a, 0x0e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x73, 0x75, 0x63, 0x22, 0x45, 0x0a, 0x0f, 0x53, 0x65, 0x6c, 0x6c, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x21, 0x0a,
	0x0d, 0x53, 0x65, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x75, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x75, 0x63,
	0x22, 0x11, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x6c, 0x44,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x69, 0x76, 0x65,
	0x55, 0x70, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a,
	0x0f, 0x47, 0x69, 0x76, 0x65, 0x55, 0x70, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x10, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x6b, 0x69, 0x70, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x6b, 0x69, 0x70, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xe7, 0x05, 0x0a, 0x04, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x45, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4e, 0x65, 0x77,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4e, 0x65, 0x77, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x45, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x42, 0x75, 0x66, 0x66, 0x12, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73,
	0x65, 0x42, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65,
	0x42, 0x75, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x07, 0x4f, 0x75, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x48, 0x0a, 0x08, 0x53, 0x65, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e,
	0x0a, 0x0a, 0x47, 0x69, 0x76, 0x65, 0x55, 0x70, 0x44, 0x69, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x69, 0x76,
	0x65, 0x55, 0x70, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47,
	0x69, 0x76, 0x65, 0x55, 0x70, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45,
	0x0a, 0x07, 0x55, 0x73, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x54, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x54, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x09, 0x53, 0x6b, 0x69, 0x70, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x53, 0x6b, 0x69, 0x70, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x6b, 0x69, 0x70, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x57, 0x61, 0x79, 0x6c, 0x6f, 0x6e, 0x31, 0x39, 0x39, 0x31, 0x2f, 0x4b, 0x69, 0x6e, 0x67,
	0x64, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x3b, 0x72, 0x6f,
	0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_room_proto_rawDescOnce sync.Once
	file_room_room_proto_rawDescData = file_room_room_proto_rawDesc
)

func file_room_room_proto_rawDescGZIP() []byte {
	file_room_room_proto_rawDescOnce.Do(func() {
		file_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_room_proto_rawDescData)
	})
	return file_room_room_proto_rawDescData
}

var file_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_room_room_proto_goTypes = []interface{}{
	(*RoomPlayerChange)(nil),     // 0: protocol.room.RoomPlayerChange
	(*RoomInfoChange)(nil),       // 1: protocol.room.RoomInfoChange
	(*NewRoomRequest)(nil),       // 2: protocol.room.NewRoomRequest
	(*NewRoomReply)(nil),         // 3: protocol.room.NewRoomReply
	(*RoomInfoRequest)(nil),      // 4: protocol.room.RoomInfoRequest
	(*RoomInfoReply)(nil),        // 5: protocol.room.RoomInfoReply
	(*UseBuffRequest)(nil),       // 6: protocol.room.UseBuffRequest
	(*UseBuffReply)(nil),         // 7: protocol.room.UseBuffReply
	(*OutCardRequest)(nil),       // 8: protocol.room.OutCardRequest
	(*OutCardReply)(nil),         // 9: protocol.room.OutCardReply
	(*SellCardRequest)(nil),      // 10: protocol.room.SellCardRequest
	(*SellCardReply)(nil),        // 11: protocol.room.SellCardReply
	(*UseSkillRequest)(nil),      // 12: protocol.room.UseSkillRequest
	(*UseSkillReply)(nil),        // 13: protocol.room.UseSkillReply
	(*RollDiceRequest)(nil),      // 14: protocol.room.RollDiceRequest
	(*RollDiceReply)(nil),        // 15: protocol.room.RollDiceReply
	(*GiveUpDiceRequest)(nil),    // 16: protocol.room.GiveUpDiceRequest
	(*GiveUpDiceReply)(nil),      // 17: protocol.room.GiveUpDiceReply
	(*UseToolRequest)(nil),       // 18: protocol.room.UseToolRequest
	(*UseToolReply)(nil),         // 19: protocol.room.UseToolReply
	(*SkipStageRequest)(nil),     // 20: protocol.room.SkipStageRequest
	(*SkipStageReply)(nil),       // 21: protocol.room.SkipStageReply
	nil,                          // 22: protocol.room.NewRoomRequest.InfosEntry
	(*common.RoomCard)(nil),      // 23: protocol.common.RoomCard
	(*common.RoomBuf)(nil),       // 24: protocol.common.RoomBuf
	(*common.RoomSkill)(nil),     // 25: protocol.common.RoomSkill
	(*common.RewardBall)(nil),    // 26: protocol.common.RewardBall
	(*common.OperateRecord)(nil), // 27: protocol.common.OperateRecord
	(common.RoomMode)(0),         // 28: protocol.common.RoomMode
	(*common.RoomInfo)(nil),      // 29: protocol.common.RoomInfo
}
var file_room_room_proto_depIdxs = []int32{
	23, // 0: protocol.room.RoomPlayerChange.obtain_cards:type_name -> protocol.common.RoomCard
	23, // 1: protocol.room.RoomPlayerChange.lose_cards:type_name -> protocol.common.RoomCard
	24, // 2: protocol.room.RoomPlayerChange.obtain_buffs:type_name -> protocol.common.RoomBuf
	24, // 3: protocol.room.RoomPlayerChange.lose_buffs:type_name -> protocol.common.RoomBuf
	25, // 4: protocol.room.RoomPlayerChange.obtain_skills:type_name -> protocol.common.RoomSkill
	25, // 5: protocol.room.RoomPlayerChange.lose_skills:type_name -> protocol.common.RoomSkill
	0,  // 6: protocol.room.RoomInfoChange.players:type_name -> protocol.room.RoomPlayerChange
	26, // 7: protocol.room.RoomInfoChange.ball:type_name -> protocol.common.RewardBall
	27, // 8: protocol.room.RoomInfoChange.record:type_name -> protocol.common.OperateRecord
	28, // 9: protocol.room.NewRoomRequest.mode:type_name -> protocol.common.RoomMode
	22, // 10: protocol.room.NewRoomRequest.Infos:type_name -> protocol.room.NewRoomRequest.InfosEntry
	29, // 11: protocol.room.NewRoomReply.room_info:type_name -> protocol.common.RoomInfo
	29, // 12: protocol.room.RoomInfoReply.room_info:type_name -> protocol.common.RoomInfo
	2,  // 13: protocol.room.Room.NewRoom:input_type -> protocol.room.NewRoomRequest
	4,  // 14: protocol.room.Room.RoomInfo:input_type -> protocol.room.RoomInfoRequest
	6,  // 15: protocol.room.Room.UseBuff:input_type -> protocol.room.UseBuffRequest
	8,  // 16: protocol.room.Room.OutCard:input_type -> protocol.room.OutCardRequest
	10, // 17: protocol.room.Room.SellCard:input_type -> protocol.room.SellCardRequest
	12, // 18: protocol.room.Room.UseSkill:input_type -> protocol.room.UseSkillRequest
	14, // 19: protocol.room.Room.RollDice:input_type -> protocol.room.RollDiceRequest
	16, // 20: protocol.room.Room.GiveUpDice:input_type -> protocol.room.GiveUpDiceRequest
	18, // 21: protocol.room.Room.UseTool:input_type -> protocol.room.UseToolRequest
	20, // 22: protocol.room.Room.SkipStage:input_type -> protocol.room.SkipStageRequest
	3,  // 23: protocol.room.Room.NewRoom:output_type -> protocol.room.NewRoomReply
	5,  // 24: protocol.room.Room.RoomInfo:output_type -> protocol.room.RoomInfoReply
	7,  // 25: protocol.room.Room.UseBuff:output_type -> protocol.room.UseBuffReply
	9,  // 26: protocol.room.Room.OutCard:output_type -> protocol.room.OutCardReply
	11, // 27: protocol.room.Room.SellCard:output_type -> protocol.room.SellCardReply
	13, // 28: protocol.room.Room.UseSkill:output_type -> protocol.room.UseSkillReply
	15, // 29: protocol.room.Room.RollDice:output_type -> protocol.room.RollDiceReply
	17, // 30: protocol.room.Room.GiveUpDice:output_type -> protocol.room.GiveUpDiceReply
	19, // 31: protocol.room.Room.UseTool:output_type -> protocol.room.UseToolReply
	21, // 32: protocol.room.Room.SkipStage:output_type -> protocol.room.SkipStageReply
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_room_room_proto_init() }
func file_room_room_proto_init() {
	if File_room_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayerChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseBuffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseBuffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellCardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseSkillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseSkillReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollDiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollDiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveUpDiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveUpDiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseToolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseToolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_room_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipStageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_room_proto_goTypes,
		DependencyIndexes: file_room_room_proto_depIdxs,
		MessageInfos:      file_room_room_proto_msgTypes,
	}.Build()
	File_room_room_proto = out.File
	file_room_room_proto_rawDesc = nil
	file_room_room_proto_goTypes = nil
	file_room_room_proto_depIdxs = nil
}
