// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: Protocol/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginType 登录类型
type LoginType int32

const (
	LoginType_guest   LoginType = 0 //游客登录
	LoginType_UserPwd LoginType = 1 //用户密码登录
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "guest",
		1: "UserPwd",
	}
	LoginType_value = map[string]int32{
		"guest":   0,
		"UserPwd": 1,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_Protocol_common_common_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_Protocol_common_common_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{0}
}

// ProtocolType 协议类型
type ProtocolType int32

const (
	ProtocolType_ws  ProtocolType = 0 //web socket
	ProtocolType_tcp ProtocolType = 1 //tcp
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "ws",
		1: "tcp",
	}
	ProtocolType_value = map[string]int32{
		"ws":  0,
		"tcp": 1,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_Protocol_common_common_proto_enumTypes[1].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_Protocol_common_common_proto_enumTypes[1]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{1}
}

// RoomMode 房间模式
type RoomMode int32

const (
	RoomMode_one_vs_one     RoomMode = 0 //1 v 1
	RoomMode_chaos_faction  RoomMode = 1 //大乱斗
	RoomMode_three_vs_three RoomMode = 2 //3 v 3
	RoomMode_five_vs_five   RoomMode = 3 //5 v 5
)

// Enum value maps for RoomMode.
var (
	RoomMode_name = map[int32]string{
		0: "one_vs_one",
		1: "chaos_faction",
		2: "three_vs_three",
		3: "five_vs_five",
	}
	RoomMode_value = map[string]int32{
		"one_vs_one":     0,
		"chaos_faction":  1,
		"three_vs_three": 2,
		"five_vs_five":   3,
	}
)

func (x RoomMode) Enum() *RoomMode {
	p := new(RoomMode)
	*p = x
	return p
}

func (x RoomMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMode) Descriptor() protoreflect.EnumDescriptor {
	return file_Protocol_common_common_proto_enumTypes[2].Descriptor()
}

func (RoomMode) Type() protoreflect.EnumType {
	return &file_Protocol_common_common_proto_enumTypes[2]
}

func (x RoomMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMode.Descriptor instead.
func (RoomMode) EnumDescriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{2}
}

// HeroMatchState 英雄匹配中状态
type HeroMatchState int32

const (
	HeroMatchState_free     HeroMatchState = 0 //空闲
	HeroMatchState_selected HeroMatchState = 1 //已选
	HeroMatchState_disabled HeroMatchState = 2 //禁用
)

// Enum value maps for HeroMatchState.
var (
	HeroMatchState_name = map[int32]string{
		0: "free",
		1: "selected",
		2: "disabled",
	}
	HeroMatchState_value = map[string]int32{
		"free":     0,
		"selected": 1,
		"disabled": 2,
	}
)

func (x HeroMatchState) Enum() *HeroMatchState {
	p := new(HeroMatchState)
	*p = x
	return p
}

func (x HeroMatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeroMatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_Protocol_common_common_proto_enumTypes[3].Descriptor()
}

func (HeroMatchState) Type() protoreflect.EnumType {
	return &file_Protocol_common_common_proto_enumTypes[3]
}

func (x HeroMatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeroMatchState.Descriptor instead.
func (HeroMatchState) EnumDescriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{3}
}

// User 用户结构体
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Hero 英雄
type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId int32          `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	State  HeroMatchState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.common.HeroMatchState" json:"state,omitempty"`
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_Protocol_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *Hero) GetState() HeroMatchState {
	if x != nil {
		return x.State
	}
	return HeroMatchState_free
}

var File_Protocol_common_common_proto protoreflect.FileDescriptor

var file_Protocol_common_common_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0x1f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x56, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49,
	0x64, 0x12, 0x35, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x23, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x10, 0x01, 0x2a, 0x1f, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x77, 0x73, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x74, 0x63, 0x70, 0x10, 0x01, 0x2a, 0x53,
	0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x6f, 0x6e,
	0x65, 0x5f, 0x76, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x63, 0x68,
	0x61, 0x6f, 0x73, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x74, 0x68, 0x72, 0x65, 0x65, 0x5f, 0x76, 0x73, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x65, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x66, 0x69, 0x76, 0x65, 0x5f, 0x76, 0x73, 0x5f, 0x66, 0x69, 0x76,
	0x65, 0x10, 0x03, 0x2a, 0x36, 0x0a, 0x0e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Protocol_common_common_proto_rawDescOnce sync.Once
	file_Protocol_common_common_proto_rawDescData = file_Protocol_common_common_proto_rawDesc
)

func file_Protocol_common_common_proto_rawDescGZIP() []byte {
	file_Protocol_common_common_proto_rawDescOnce.Do(func() {
		file_Protocol_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protocol_common_common_proto_rawDescData)
	})
	return file_Protocol_common_common_proto_rawDescData
}

var file_Protocol_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Protocol_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Protocol_common_common_proto_goTypes = []interface{}{
	(LoginType)(0),      // 0: protocol.common.LoginType
	(ProtocolType)(0),   // 1: protocol.common.ProtocolType
	(RoomMode)(0),       // 2: protocol.common.RoomMode
	(HeroMatchState)(0), // 3: protocol.common.HeroMatchState
	(*User)(nil),        // 4: protocol.common.User
	(*Hero)(nil),        // 5: protocol.common.Hero
}
var file_Protocol_common_common_proto_depIdxs = []int32{
	3, // 0: protocol.common.Hero.state:type_name -> protocol.common.HeroMatchState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protocol_common_common_proto_init() }
func file_Protocol_common_common_proto_init() {
	if File_Protocol_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protocol_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protocol_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protocol_common_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protocol_common_common_proto_goTypes,
		DependencyIndexes: file_Protocol_common_common_proto_depIdxs,
		EnumInfos:         file_Protocol_common_common_proto_enumTypes,
		MessageInfos:      file_Protocol_common_common_proto_msgTypes,
	}.Build()
	File_Protocol_common_common_proto = out.File
	file_Protocol_common_common_proto_rawDesc = nil
	file_Protocol_common_common_proto_goTypes = nil
	file_Protocol_common_common_proto_depIdxs = nil
}
