// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginType 登录类型
type LoginType int32

const (
	LoginType_guest   LoginType = 0 //游客登录
	LoginType_UserPwd LoginType = 1 //用户密码登录
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "guest",
		1: "UserPwd",
	}
	LoginType_value = map[string]int32{
		"guest":   0,
		"UserPwd": 1,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

// ProtocolType 协议类型
type ProtocolType int32

const (
	ProtocolType_ws  ProtocolType = 0 // web socket
	ProtocolType_tcp ProtocolType = 1 // tcp
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "ws",
		1: "tcp",
	}
	ProtocolType_value = map[string]int32{
		"ws":  0,
		"tcp": 1,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

// RoomMode 房间模式
type RoomMode int32

const (
	RoomMode_one_vs_one     RoomMode = 0 // 1 v 1
	RoomMode_chaos_faction  RoomMode = 1 //大乱斗
	RoomMode_three_vs_three RoomMode = 2 // 3 v 3
	RoomMode_five_vs_five   RoomMode = 3 // 5 v 5
)

// Enum value maps for RoomMode.
var (
	RoomMode_name = map[int32]string{
		0: "one_vs_one",
		1: "chaos_faction",
		2: "three_vs_three",
		3: "five_vs_five",
	}
	RoomMode_value = map[string]int32{
		"one_vs_one":     0,
		"chaos_faction":  1,
		"three_vs_three": 2,
		"five_vs_five":   3,
	}
)

func (x RoomMode) Enum() *RoomMode {
	p := new(RoomMode)
	*p = x
	return p
}

func (x RoomMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (RoomMode) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x RoomMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMode.Descriptor instead.
func (RoomMode) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

// HeroMatchState 英雄匹配中状态
type HeroMatchState int32

const (
	HeroMatchState_free     HeroMatchState = 0 //空闲
	HeroMatchState_selected HeroMatchState = 1 //已选
	HeroMatchState_disabled HeroMatchState = 2 //禁用
)

// Enum value maps for HeroMatchState.
var (
	HeroMatchState_name = map[int32]string{
		0: "free",
		1: "selected",
		2: "disabled",
	}
	HeroMatchState_value = map[string]int32{
		"free":     0,
		"selected": 1,
		"disabled": 2,
	}
)

func (x HeroMatchState) Enum() *HeroMatchState {
	p := new(HeroMatchState)
	*p = x
	return p
}

func (x HeroMatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeroMatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[3].Descriptor()
}

func (HeroMatchState) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[3]
}

func (x HeroMatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeroMatchState.Descriptor instead.
func (HeroMatchState) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

//-------------------------------room enum--------------------------------//
// ActorRace 角色种族
type ActorRace int32

const (
	ActorRace_race_qt ActorRace = 0 //其他
	ActorRace_race_rZ ActorRace = 1 //人族
	ActorRace_race_sr ActorRace = 2 //兽人
	ActorRace_race_jl ActorRace = 3 //精灵
	ActorRace_race_sz ActorRace = 4 //神族
)

// Enum value maps for ActorRace.
var (
	ActorRace_name = map[int32]string{
		0: "race_qt",
		1: "race_rZ",
		2: "race_sr",
		3: "race_jl",
		4: "race_sz",
	}
	ActorRace_value = map[string]int32{
		"race_qt": 0,
		"race_rZ": 1,
		"race_sr": 2,
		"race_jl": 3,
		"race_sz": 4,
	}
)

func (x ActorRace) Enum() *ActorRace {
	p := new(ActorRace)
	*p = x
	return p
}

func (x ActorRace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorRace) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[4].Descriptor()
}

func (ActorRace) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[4]
}

func (x ActorRace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorRace.Descriptor instead.
func (ActorRace) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

// ActorSex 角色性别
type ActorSex int32

const (
	ActorSex_sex_woman ActorSex = 0 //女性
	ActorSex_sex_man   ActorSex = 1 //男性
)

// Enum value maps for ActorSex.
var (
	ActorSex_name = map[int32]string{
		0: "sex_woman",
		1: "sex_man",
	}
	ActorSex_value = map[string]int32{
		"sex_woman": 0,
		"sex_man":   1,
	}
)

func (x ActorSex) Enum() *ActorSex {
	p := new(ActorSex)
	*p = x
	return p
}

func (x ActorSex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorSex) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[5].Descriptor()
}

func (ActorSex) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[5]
}

func (x ActorSex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorSex.Descriptor instead.
func (ActorSex) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

// ActorPro 角色职业
type ActorPro int32

const (
	ActorPro_pro_other ActorPro = 0 //其他
	ActorPro_pro_sc    ActorPro = 1 //输出
	ActorPro_pro_fs    ActorPro = 2 //法师
	ActorPro_pro_zs    ActorPro = 3 //战士
	ActorPro_pro_tk    ActorPro = 4 //坦克
	ActorPro_pro_ck    ActorPro = 5 //刺客
)

// Enum value maps for ActorPro.
var (
	ActorPro_name = map[int32]string{
		0: "pro_other",
		1: "pro_sc",
		2: "pro_fs",
		3: "pro_zs",
		4: "pro_tk",
		5: "pro_ck",
	}
	ActorPro_value = map[string]int32{
		"pro_other": 0,
		"pro_sc":    1,
		"pro_fs":    2,
		"pro_zs":    3,
		"pro_tk":    4,
		"pro_ck":    5,
	}
)

func (x ActorPro) Enum() *ActorPro {
	p := new(ActorPro)
	*p = x
	return p
}

func (x ActorPro) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorPro) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[6].Descriptor()
}

func (ActorPro) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[6]
}

func (x ActorPro) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorPro.Descriptor instead.
func (ActorPro) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

// EffectWay 生效方式
type EffectWay int32

const (
	EffectWay_active  EffectWay = 0 //主动
	EffectWay_passive EffectWay = 1 //被动
)

// Enum value maps for EffectWay.
var (
	EffectWay_name = map[int32]string{
		0: "active",
		1: "passive",
	}
	EffectWay_value = map[string]int32{
		"active":  0,
		"passive": 1,
	}
)

func (x EffectWay) Enum() *EffectWay {
	p := new(EffectWay)
	*p = x
	return p
}

func (x EffectWay) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectWay) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[7].Descriptor()
}

func (EffectWay) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[7]
}

func (x EffectWay) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectWay.Descriptor instead.
func (EffectWay) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{7}
}

// HurtKind 伤害类型
type HurtKind int32

const (
	HurtKind_hurt_normal HurtKind = 0 //普通伤害
	HurtKind_hurt_real   HurtKind = 1 //真实伤害
	HurtKind_hurt_attach HurtKind = 2 //附属伤害
	HurtKind_hurt_final  HurtKind = 3 //终极伤害
)

// Enum value maps for HurtKind.
var (
	HurtKind_name = map[int32]string{
		0: "hurt_normal",
		1: "hurt_real",
		2: "hurt_attach",
		3: "hurt_final",
	}
	HurtKind_value = map[string]int32{
		"hurt_normal": 0,
		"hurt_real":   1,
		"hurt_attach": 2,
		"hurt_final":  3,
	}
)

func (x HurtKind) Enum() *HurtKind {
	p := new(HurtKind)
	*p = x
	return p
}

func (x HurtKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HurtKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[8].Descriptor()
}

func (HurtKind) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[8]
}

func (x HurtKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HurtKind.Descriptor instead.
func (HurtKind) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{8}
}

// GameStage 游戏阶段
type GameStage int32

const (
	GameStage_gs_keep      GameStage = 0 //维持阶段
	GameStage_gs_income    GameStage = 1 //收入阶段
	GameStage_gs_main      GameStage = 2 //主要阶段
	GameStage_gs_offensive GameStage = 3 //进攻投掷阶段
	GameStage_gs_enemy     GameStage = 4 //索敌投掷阶段
	GameStage_gs_defensive GameStage = 5 //防御阶段
	GameStage_gs_finish    GameStage = 6 //收尾阶段
)

// Enum value maps for GameStage.
var (
	GameStage_name = map[int32]string{
		0: "gs_keep",
		1: "gs_income",
		2: "gs_main",
		3: "gs_offensive",
		4: "gs_enemy",
		5: "gs_defensive",
		6: "gs_finish",
	}
	GameStage_value = map[string]int32{
		"gs_keep":      0,
		"gs_income":    1,
		"gs_main":      2,
		"gs_offensive": 3,
		"gs_enemy":     4,
		"gs_defensive": 5,
		"gs_finish":    6,
	}
)

func (x GameStage) Enum() *GameStage {
	p := new(GameStage)
	*p = x
	return p
}

func (x GameStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStage) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[9].Descriptor()
}

func (GameStage) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[9]
}

func (x GameStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStage.Descriptor instead.
func (GameStage) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{9}
}

// CardKind 卡牌类型
type CardKind int32

const (
	CardKind_card_function CardKind = 0 //功能牌
	CardKind_card_upgrade  CardKind = 1 //升级牌
	CardKind_card_action   CardKind = 2 //行动牌
)

// Enum value maps for CardKind.
var (
	CardKind_name = map[int32]string{
		0: "card_function",
		1: "card_upgrade",
		2: "card_action",
	}
	CardKind_value = map[string]int32{
		"card_function": 0,
		"card_upgrade":  1,
		"card_action":   2,
	}
)

func (x CardKind) Enum() *CardKind {
	p := new(CardKind)
	*p = x
	return p
}

func (x CardKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[10].Descriptor()
}

func (CardKind) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[10]
}

func (x CardKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardKind.Descriptor instead.
func (CardKind) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{10}
}

// CardLevel 卡牌等级
type CardLevel int32

const (
	CardLevel_card_common   CardLevel = 0 //普通
	CardLevel_card_uncommon CardLevel = 1 //稀有
	CardLevel_card_epic     CardLevel = 2 //史诗
	CardLevel_card_legend   CardLevel = 3 //传说
	CardLevel_card_deep     CardLevel = 4 //深渊
)

// Enum value maps for CardLevel.
var (
	CardLevel_name = map[int32]string{
		0: "card_common",
		1: "card_uncommon",
		2: "card_epic",
		3: "card_legend",
		4: "card_deep",
	}
	CardLevel_value = map[string]int32{
		"card_common":   0,
		"card_uncommon": 1,
		"card_epic":     2,
		"card_legend":   3,
		"card_deep":     4,
	}
)

func (x CardLevel) Enum() *CardLevel {
	p := new(CardLevel)
	*p = x
	return p
}

func (x CardLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[11].Descriptor()
}

func (CardLevel) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[11]
}

func (x CardLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardLevel.Descriptor instead.
func (CardLevel) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{11}
}

// CardState 卡牌状态
type CardState int32

const (
	CardState_card_enabled  CardState = 0 //可用
	CardState_card_disabled CardState = 1 //不可用
)

// Enum value maps for CardState.
var (
	CardState_name = map[int32]string{
		0: "card_enabled",
		1: "card_disabled",
	}
	CardState_value = map[string]int32{
		"card_enabled":  0,
		"card_disabled": 1,
	}
)

func (x CardState) Enum() *CardState {
	p := new(CardState)
	*p = x
	return p
}

func (x CardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[12].Descriptor()
}

func (CardState) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[12]
}

func (x CardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardState.Descriptor instead.
func (CardState) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{12}
}

// CardObject 卡牌对象
type CardObject int32

const (
	CardObject_card_self  CardObject = 0 //自己
	CardObject_card_enemy CardObject = 1 //敌人
	CardObject_card_all   CardObject = 2 //所有人
)

// Enum value maps for CardObject.
var (
	CardObject_name = map[int32]string{
		0: "card_self",
		1: "card_enemy",
		2: "card_all",
	}
	CardObject_value = map[string]int32{
		"card_self":  0,
		"card_enemy": 1,
		"card_all":   2,
	}
)

func (x CardObject) Enum() *CardObject {
	p := new(CardObject)
	*p = x
	return p
}

func (x CardObject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardObject) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[13].Descriptor()
}

func (CardObject) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[13]
}

func (x CardObject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardObject.Descriptor instead.
func (CardObject) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{13}
}

// BuffKind buff类型
type BuffKind int32

const (
	BuffKind_buff_positive BuffKind = 0 //正面
	BuffKind_buff_negative BuffKind = 1 //负面
)

// Enum value maps for BuffKind.
var (
	BuffKind_name = map[int32]string{
		0: "buff_positive",
		1: "buff_negative",
	}
	BuffKind_value = map[string]int32{
		"buff_positive": 0,
		"buff_negative": 1,
	}
)

func (x BuffKind) Enum() *BuffKind {
	p := new(BuffKind)
	*p = x
	return p
}

func (x BuffKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuffKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[14].Descriptor()
}

func (BuffKind) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[14]
}

func (x BuffKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuffKind.Descriptor instead.
func (BuffKind) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{14}
}

// BuffState buff状态
type BuffState int32

const (
	BuffState_buff_enabled  BuffState = 0 //可用
	BuffState_buff_disabled BuffState = 1 //不可用
)

// Enum value maps for BuffState.
var (
	BuffState_name = map[int32]string{
		0: "buff_enabled",
		1: "buff_disabled",
	}
	BuffState_value = map[string]int32{
		"buff_enabled":  0,
		"buff_disabled": 1,
	}
)

func (x BuffState) Enum() *BuffState {
	p := new(BuffState)
	*p = x
	return p
}

func (x BuffState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuffState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[15].Descriptor()
}

func (BuffState) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[15]
}

func (x BuffState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuffState.Descriptor instead.
func (BuffState) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{15}
}

// BuffEffect buff效果
type BuffEffect int32

const (
	BuffEffect_buff_add_control   BuffEffect = 0  //控制
	BuffEffect_buff_sub_control   BuffEffect = 1  //解控
	BuffEffect_buff_avoid_control BuffEffect = 2  //免控
	BuffEffect_buff_add_hurt      BuffEffect = 3  //增伤
	BuffEffect_buff_sub_hurt      BuffEffect = 4  //减伤
	BuffEffect_buff_avoid_effect  BuffEffect = 5  //免伤
	BuffEffect_buff_add_effect    BuffEffect = 6  //增效
	BuffEffect_buff_sub_effect    BuffEffect = 7  //减效
	BuffEffect_buff_revive        BuffEffect = 8  //复活
	BuffEffect_buff_add_defense   BuffEffect = 9  //增防
	BuffEffect_buff_sub_defense   BuffEffect = 10 //减防
)

// Enum value maps for BuffEffect.
var (
	BuffEffect_name = map[int32]string{
		0:  "buff_add_control",
		1:  "buff_sub_control",
		2:  "buff_avoid_control",
		3:  "buff_add_hurt",
		4:  "buff_sub_hurt",
		5:  "buff_avoid_effect",
		6:  "buff_add_effect",
		7:  "buff_sub_effect",
		8:  "buff_revive",
		9:  "buff_add_defense",
		10: "buff_sub_defense",
	}
	BuffEffect_value = map[string]int32{
		"buff_add_control":   0,
		"buff_sub_control":   1,
		"buff_avoid_control": 2,
		"buff_add_hurt":      3,
		"buff_sub_hurt":      4,
		"buff_avoid_effect":  5,
		"buff_add_effect":    6,
		"buff_sub_effect":    7,
		"buff_revive":        8,
		"buff_add_defense":   9,
		"buff_sub_defense":   10,
	}
)

func (x BuffEffect) Enum() *BuffEffect {
	p := new(BuffEffect)
	*p = x
	return p
}

func (x BuffEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuffEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[16].Descriptor()
}

func (BuffEffect) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[16]
}

func (x BuffEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuffEffect.Descriptor instead.
func (BuffEffect) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{16}
}

// BuffLife buff生命周期
type BuffLife int32

const (
	BuffLife_buff_single  BuffLife = 0 //一次性
	BuffLife_buff_forever BuffLife = 1 //永久
)

// Enum value maps for BuffLife.
var (
	BuffLife_name = map[int32]string{
		0: "buff_single",
		1: "buff_forever",
	}
	BuffLife_value = map[string]int32{
		"buff_single":  0,
		"buff_forever": 1,
	}
)

func (x BuffLife) Enum() *BuffLife {
	p := new(BuffLife)
	*p = x
	return p
}

func (x BuffLife) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuffLife) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[17].Descriptor()
}

func (BuffLife) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[17]
}

func (x BuffLife) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuffLife.Descriptor instead.
func (BuffLife) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{17}
}

// SkillState 技能状态
type SkillState int32

const (
	SkillState_skill_enabled  SkillState = 0 //可用
	SkillState_skill_disabled SkillState = 1 //不可用
)

// Enum value maps for SkillState.
var (
	SkillState_name = map[int32]string{
		0: "skill_enabled",
		1: "skill_disabled",
	}
	SkillState_value = map[string]int32{
		"skill_enabled":  0,
		"skill_disabled": 1,
	}
)

func (x SkillState) Enum() *SkillState {
	p := new(SkillState)
	*p = x
	return p
}

func (x SkillState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[18].Descriptor()
}

func (SkillState) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[18]
}

func (x SkillState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillState.Descriptor instead.
func (SkillState) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{18}
}

// DiceFaceNumber 筛子数字
type DiceFaceNumber int32

const (
	DiceFaceNumber_dice_number_null DiceFaceNumber = 0 //非法面值
	DiceFaceNumber_dice_number_1    DiceFaceNumber = 1
	DiceFaceNumber_dice_number_2    DiceFaceNumber = 2
	DiceFaceNumber_dice_number_3    DiceFaceNumber = 3
	DiceFaceNumber_dice_number_4    DiceFaceNumber = 4
	DiceFaceNumber_dice_number_5    DiceFaceNumber = 5
	DiceFaceNumber_dice_number_6    DiceFaceNumber = 6
)

// Enum value maps for DiceFaceNumber.
var (
	DiceFaceNumber_name = map[int32]string{
		0: "dice_number_null",
		1: "dice_number_1",
		2: "dice_number_2",
		3: "dice_number_3",
		4: "dice_number_4",
		5: "dice_number_5",
		6: "dice_number_6",
	}
	DiceFaceNumber_value = map[string]int32{
		"dice_number_null": 0,
		"dice_number_1":    1,
		"dice_number_2":    2,
		"dice_number_3":    3,
		"dice_number_4":    4,
		"dice_number_5":    5,
		"dice_number_6":    6,
	}
)

func (x DiceFaceNumber) Enum() *DiceFaceNumber {
	p := new(DiceFaceNumber)
	*p = x
	return p
}

func (x DiceFaceNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiceFaceNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[19].Descriptor()
}

func (DiceFaceNumber) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[19]
}

func (x DiceFaceNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiceFaceNumber.Descriptor instead.
func (DiceFaceNumber) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{19}
}

// DiceFacePic 筛子图案
type DiceFacePic int32

const (
	DiceFacePic_dice_pic_null DiceFacePic = 0 //非法面值
	DiceFacePic_dice_pic_A    DiceFacePic = 1
	DiceFacePic_dice_pic_B    DiceFacePic = 2
	DiceFacePic_dice_pic_C    DiceFacePic = 3
)

// Enum value maps for DiceFacePic.
var (
	DiceFacePic_name = map[int32]string{
		0: "dice_pic_null",
		1: "dice_pic_A",
		2: "dice_pic_B",
		3: "dice_pic_C",
	}
	DiceFacePic_value = map[string]int32{
		"dice_pic_null": 0,
		"dice_pic_A":    1,
		"dice_pic_B":    2,
		"dice_pic_C":    3,
	}
)

func (x DiceFacePic) Enum() *DiceFacePic {
	p := new(DiceFacePic)
	*p = x
	return p
}

func (x DiceFacePic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiceFacePic) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[20].Descriptor()
}

func (DiceFacePic) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[20]
}

func (x DiceFacePic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiceFacePic.Descriptor instead.
func (DiceFacePic) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{20}
}

// OperateKind 操作种类
type OperateKind int32

const (
	OperateKind_ok_null         OperateKind = 0 //空操作
	OperateKind_ok_skip         OperateKind = 1 //跳过该阶段
	OperateKind_ok_out_card     OperateKind = 2 //打出卡牌
	OperateKind_ok_sell_card    OperateKind = 3 //出售卡牌
	OperateKind_ok_roll_dice    OperateKind = 4 //掷骰子
	OperateKind_ok_send_skill   OperateKind = 5 //发动技能
	OperateKind_ok_trigger_buff OperateKind = 6 //触发buff
)

// Enum value maps for OperateKind.
var (
	OperateKind_name = map[int32]string{
		0: "ok_null",
		1: "ok_skip",
		2: "ok_out_card",
		3: "ok_sell_card",
		4: "ok_roll_dice",
		5: "ok_send_skill",
		6: "ok_trigger_buff",
	}
	OperateKind_value = map[string]int32{
		"ok_null":         0,
		"ok_skip":         1,
		"ok_out_card":     2,
		"ok_sell_card":    3,
		"ok_roll_dice":    4,
		"ok_send_skill":   5,
		"ok_trigger_buff": 6,
	}
)

func (x OperateKind) Enum() *OperateKind {
	p := new(OperateKind)
	*p = x
	return p
}

func (x OperateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[21].Descriptor()
}

func (OperateKind) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[21]
}

func (x OperateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperateKind.Descriptor instead.
func (OperateKind) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{21}
}

// User 用户结构体
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Hero 英雄
type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId int32          `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	State  HeroMatchState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.common.HeroMatchState" json:"state,omitempty"`
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *Hero) GetState() HeroMatchState {
	if x != nil {
		return x.State
	}
	return HeroMatchState_free
}

// SelectInfo 选择的信息
type SelectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //用户信息
	HeroId int32 `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` //英雄信息
}

func (x *SelectInfo) Reset() {
	*x = SelectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectInfo) ProtoMessage() {}

func (x *SelectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectInfo.ProtoReflect.Descriptor instead.
func (*SelectInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *SelectInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SelectInfo) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

//-------------------------------room struct--------------------------------//
// RoomCard 卡牌
type RoomCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      //卡牌id
	State CardState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.common.CardState" json:"state,omitempty"` //卡牌状态
}

func (x *RoomCard) Reset() {
	*x = RoomCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCard) ProtoMessage() {}

func (x *RoomCard) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCard.ProtoReflect.Descriptor instead.
func (*RoomCard) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *RoomCard) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomCard) GetState() CardState {
	if x != nil {
		return x.State
	}
	return CardState_card_enabled
}

// RoomBuf buff
type RoomBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // buff id
	Num   int32     `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                                    // buff 个数
	State BuffState `protobuf:"varint,3,opt,name=state,proto3,enum=protocol.common.BuffState" json:"state,omitempty"` // buff 状态
}

func (x *RoomBuf) Reset() {
	*x = RoomBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBuf) ProtoMessage() {}

func (x *RoomBuf) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBuf.ProtoReflect.Descriptor instead.
func (*RoomBuf) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *RoomBuf) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomBuf) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *RoomBuf) GetState() BuffState {
	if x != nil {
		return x.State
	}
	return BuffState_buff_enabled
}

// skill
type RoomSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                       //技能 id
	State SkillState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.common.SkillState" json:"state,omitempty"` //技能状态
}

func (x *RoomSkill) Reset() {
	*x = RoomSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSkill) ProtoMessage() {}

func (x *RoomSkill) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSkill.ProtoReflect.Descriptor instead.
func (*RoomSkill) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *RoomSkill) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomSkill) GetState() SkillState {
	if x != nil {
		return x.State
	}
	return SkillState_skill_enabled
}

// DiceFace 筛子面
type DiceFace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num DiceFaceNumber `protobuf:"varint,1,opt,name=num,proto3,enum=protocol.common.DiceFaceNumber" json:"num,omitempty"`
	Pic DiceFacePic    `protobuf:"varint,2,opt,name=pic,proto3,enum=protocol.common.DiceFacePic" json:"pic,omitempty"`
}

func (x *DiceFace) Reset() {
	*x = DiceFace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceFace) ProtoMessage() {}

func (x *DiceFace) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceFace.ProtoReflect.Descriptor instead.
func (*DiceFace) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *DiceFace) GetNum() DiceFaceNumber {
	if x != nil {
		return x.Num
	}
	return DiceFaceNumber_dice_number_null
}

func (x *DiceFace) GetPic() DiceFacePic {
	if x != nil {
		return x.Pic
	}
	return DiceFacePic_dice_pic_null
}

// RoomDice 1个筛子 6个面
type RoomDice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Df []*DiceFace `protobuf:"bytes,1,rep,name=df,proto3" json:"df,omitempty"` //筛子的6个面
}

func (x *RoomDice) Reset() {
	*x = RoomDice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomDice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDice) ProtoMessage() {}

func (x *RoomDice) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDice.ProtoReflect.Descriptor instead.
func (*RoomDice) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *RoomDice) GetDf() []*DiceFace {
	if x != nil {
		return x.Df
	}
	return nil
}

//玩家信息
type RoomPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32            `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                             //玩家id
	Seat      int32            `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`                                               //玩家座位号
	HeroId    int32            `protobuf:"varint,3,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`                             //英雄id
	Blood     int32            `protobuf:"varint,4,opt,name=blood,proto3" json:"blood,omitempty"`                                             //血量
	Cp        int32            `protobuf:"varint,5,opt,name=cp,proto3" json:"cp,omitempty"`                                                   //战斗点数
	LeftCards []*RoomCard      `protobuf:"bytes,6,rep,name=left_cards,json=leftCards,proto3" json:"left_cards,omitempty"`                     //牌堆列表
	HandCards []*RoomCard      `protobuf:"bytes,7,rep,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`                     //手牌列表
	DisCards  []*RoomCard      `protobuf:"bytes,8,rep,name=dis_cards,json=disCards,proto3" json:"dis_cards,omitempty"`                        //出牌列表
	Buffs     []*RoomBuf       `protobuf:"bytes,9,rep,name=buffs,proto3" json:"buffs,omitempty"`                                              // buff列表
	Skills    []*RoomSkill     `protobuf:"bytes,10,rep,name=skills,proto3" json:"skills,omitempty"`                                           //技能列表
	Dices     []DiceFaceNumber `protobuf:"varint,11,rep,packed,name=dices,proto3,enum=protocol.common.DiceFaceNumber" json:"dices,omitempty"` //掷骰子的结果（如： 1 ，1，1），根据英雄筛子的初始配置，拿到图案
	LeftTime  int32            `protobuf:"varint,12,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`                      //剩余时间（s）
}

func (x *RoomPlayerInfo) Reset() {
	*x = RoomPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerInfo) ProtoMessage() {}

func (x *RoomPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerInfo.ProtoReflect.Descriptor instead.
func (*RoomPlayerInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *RoomPlayerInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomPlayerInfo) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *RoomPlayerInfo) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *RoomPlayerInfo) GetBlood() int32 {
	if x != nil {
		return x.Blood
	}
	return 0
}

func (x *RoomPlayerInfo) GetCp() int32 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *RoomPlayerInfo) GetLeftCards() []*RoomCard {
	if x != nil {
		return x.LeftCards
	}
	return nil
}

func (x *RoomPlayerInfo) GetHandCards() []*RoomCard {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *RoomPlayerInfo) GetDisCards() []*RoomCard {
	if x != nil {
		return x.DisCards
	}
	return nil
}

func (x *RoomPlayerInfo) GetBuffs() []*RoomBuf {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *RoomPlayerInfo) GetSkills() []*RoomSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *RoomPlayerInfo) GetDices() []DiceFaceNumber {
	if x != nil {
		return x.Dices
	}
	return nil
}

func (x *RoomPlayerInfo) GetLeftTime() int32 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

//操作位置信息
type OperateSeatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundSeat int32     `protobuf:"varint,1,opt,name=round_seat,json=roundSeat,proto3" json:"round_seat,omitempty"`       //当前回合的操作玩家seat
	Stage     GameStage `protobuf:"varint,2,opt,name=stage,proto3,enum=protocol.common.GameStage" json:"stage,omitempty"` //当前阶段
	StageSeat int32     `protobuf:"varint,3,opt,name=stage_seat,json=stageSeat,proto3" json:"stage_seat,omitempty"`       //当前阶段玩家seat
}

func (x *OperateSeatInfo) Reset() {
	*x = OperateSeatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateSeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateSeatInfo) ProtoMessage() {}

func (x *OperateSeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateSeatInfo.ProtoReflect.Descriptor instead.
func (*OperateSeatInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{9}
}

func (x *OperateSeatInfo) GetRoundSeat() int32 {
	if x != nil {
		return x.RoundSeat
	}
	return 0
}

func (x *OperateSeatInfo) GetStage() GameStage {
	if x != nil {
		return x.Stage
	}
	return GameStage_gs_keep
}

func (x *OperateSeatInfo) GetStageSeat() int32 {
	if x != nil {
		return x.StageSeat
	}
	return 0
}

// OperateInfo 操作信息
type OperateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatInfo   *OperateSeatInfo `protobuf:"bytes,1,opt,name=seat_info,json=seatInfo,proto3" json:"seat_info,omitempty"`               //位置信息
	EnemySeats []int32          `protobuf:"varint,2,rep,packed,name=enemy_seats,json=enemySeats,proto3" json:"enemy_seats,omitempty"` //被攻击的玩家座位号
}

func (x *OperateInfo) Reset() {
	*x = OperateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateInfo) ProtoMessage() {}

func (x *OperateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateInfo.ProtoReflect.Descriptor instead.
func (*OperateInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{10}
}

func (x *OperateInfo) GetSeatInfo() *OperateSeatInfo {
	if x != nil {
		return x.SeatInfo
	}
	return nil
}

func (x *OperateInfo) GetEnemySeats() []int32 {
	if x != nil {
		return x.EnemySeats
	}
	return nil
}

// OperateRecord 操作记录
type OperateRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32        `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                //操作序号
	Info  *OperateInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                                   //当前操作信息
	Kind  OperateKind  `protobuf:"varint,3,opt,name=kind,proto3,enum=protocol.common.OperateKind" json:"kind,omitempty"` //操作种类
	Card  *RoomCard    `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`                                   //出的牌
	Skill *RoomSkill   `protobuf:"bytes,5,opt,name=skill,proto3" json:"skill,omitempty"`                                 //技能
	Buff  *RoomBuf     `protobuf:"bytes,6,opt,name=buff,proto3" json:"buff,omitempty"`                                   // buff
	Dice  *RoomDice    `protobuf:"bytes,7,opt,name=dice,proto3" json:"dice,omitempty"`                                   //骰子
}

func (x *OperateRecord) Reset() {
	*x = OperateRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRecord) ProtoMessage() {}

func (x *OperateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRecord.ProtoReflect.Descriptor instead.
func (*OperateRecord) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{11}
}

func (x *OperateRecord) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OperateRecord) GetInfo() *OperateInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *OperateRecord) GetKind() OperateKind {
	if x != nil {
		return x.Kind
	}
	return OperateKind_ok_null
}

func (x *OperateRecord) GetCard() *RoomCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *OperateRecord) GetSkill() *RoomSkill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *OperateRecord) GetBuff() *RoomBuf {
	if x != nil {
		return x.Buff
	}
	return nil
}

func (x *OperateRecord) GetDice() *RoomDice {
	if x != nil {
		return x.Dice
	}
	return nil
}

// RewardBall 奖励球
type RewardBall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurRound   int32 `protobuf:"varint,1,opt,name=cur_round,json=curRound,proto3" json:"cur_round,omitempty"`       //当前回合数
	TotalRound int32 `protobuf:"varint,2,opt,name=total_round,json=totalRound,proto3" json:"total_round,omitempty"` //满回合数
}

func (x *RewardBall) Reset() {
	*x = RewardBall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardBall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardBall) ProtoMessage() {}

func (x *RewardBall) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardBall.ProtoReflect.Descriptor instead.
func (*RewardBall) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{12}
}

func (x *RewardBall) GetCurRound() int32 {
	if x != nil {
		return x.CurRound
	}
	return 0
}

func (x *RewardBall) GetTotalRound() int32 {
	if x != nil {
		return x.TotalRound
	}
	return 0
}

//房间基本信息
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  int32             `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`             //房间id
	Mode    RoomMode          `protobuf:"varint,2,opt,name=mode,proto3,enum=protocol.common.RoomMode" json:"mode,omitempty"` //房间模式
	Players []*RoomPlayerInfo `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`                          //房间玩家信息
	Record  []*OperateRecord  `protobuf:"bytes,4,rep,name=record,proto3" json:"record,omitempty"`                            //操作记录信息
	Ball    *RewardBall       `protobuf:"bytes,5,opt,name=ball,proto3" json:"ball,omitempty"`                                //占卜球信息
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{13}
}

func (x *RoomInfo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetMode() RoomMode {
	if x != nil {
		return x.Mode
	}
	return RoomMode_one_vs_one
}

func (x *RoomInfo) GetPlayers() []*RoomPlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfo) GetRecord() []*OperateRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RoomInfo) GetBall() *RewardBall {
	if x != nil {
		return x.Ball
	}
	return nil
}

var File_common_common_proto protoreflect.FileDescriptor

var file_common_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12,
	0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22,
	0x4c, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5d, 0x0a,
	0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x75, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x75, 0x66, 0x66,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4e, 0x0a, 0x09,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x6d, 0x0a, 0x08,
	0x44, 0x69, 0x63, 0x65, 0x46, 0x61, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x46, 0x61, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x03, 0x70,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x46,
	0x61, 0x63, 0x65, 0x50, 0x69, 0x63, 0x52, 0x03, 0x70, 0x69, 0x63, 0x22, 0x35, 0x0a, 0x08, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x02, 0x64, 0x66, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x46, 0x61, 0x63, 0x65, 0x52, 0x02,
	0x64, 0x66, 0x22, 0xe0, 0x03, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65,
	0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x6f,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63,
	0x70, 0x12, 0x38, 0x0a, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x68,
	0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x08, 0x64, 0x69, 0x73, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x2e, 0x0a,
	0x05, 0x62, 0x75, 0x66, 0x66, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x42, 0x75, 0x66, 0x52, 0x05, 0x62, 0x75, 0x66, 0x66, 0x73, 0x12, 0x32, 0x0a,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x12, 0x35, 0x0a, 0x05, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x46, 0x61, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x05, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x66,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x22, 0x6d, 0x0a, 0x0b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x73,
	0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x65, 0x6d, 0x79,
	0x5f, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6e,
	0x65, 0x6d, 0x79, 0x53, 0x65, 0x61, 0x74, 0x73, 0x22, 0xc7, 0x02, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x30, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63,
	0x61, 0x72, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x05,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x04, 0x62, 0x75, 0x66, 0x66, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x75, 0x66, 0x52, 0x04, 0x62,
	0x75, 0x66, 0x66, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x69,
	0x63, 0x65, 0x22, 0x4a, 0x0a, 0x0a, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x42, 0x61, 0x6c, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x75, 0x72, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xf6,
	0x01, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x36,
	0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x42, 0x61, 0x6c,
	0x6c, 0x52, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x2a, 0x23, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x67, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x10, 0x01, 0x2a, 0x1f, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x77, 0x73, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x74, 0x63, 0x70, 0x10, 0x01, 0x2a, 0x53, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x6f, 0x6e, 0x65,
	0x5f, 0x76, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x63, 0x68, 0x61,
	0x6f, 0x73, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x74, 0x68, 0x72, 0x65, 0x65, 0x5f, 0x76, 0x73, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x65, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x66, 0x69, 0x76, 0x65, 0x5f, 0x76, 0x73, 0x5f, 0x66, 0x69, 0x76, 0x65,
	0x10, 0x03, 0x2a, 0x36, 0x0a, 0x0e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x2a, 0x4c, 0x0a, 0x09, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x61, 0x63, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x61, 0x63, 0x65, 0x5f,
	0x71, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x72, 0x5a, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x6a, 0x6c, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x72,
	0x61, 0x63, 0x65, 0x5f, 0x73, 0x7a, 0x10, 0x04, 0x2a, 0x26, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x78, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x65, 0x78, 0x5f, 0x77, 0x6f, 0x6d, 0x61,
	0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x65, 0x78, 0x5f, 0x6d, 0x61, 0x6e, 0x10, 0x01,
	0x2a, 0x55, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x12, 0x0d, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x5f, 0x73, 0x63, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x5f, 0x66,
	0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x5f, 0x7a, 0x73, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x5f, 0x74, 0x6b, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x5f, 0x63, 0x6b, 0x10, 0x05, 0x2a, 0x24, 0x0a, 0x09, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x57, 0x61, 0x79, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x10, 0x01, 0x2a, 0x4b, 0x0a,
	0x08, 0x48, 0x75, 0x72, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x68, 0x75, 0x72,
	0x74, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x68, 0x75,
	0x72, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x68, 0x75, 0x72,
	0x74, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x68, 0x75,
	0x72, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x10, 0x03, 0x2a, 0x75, 0x0a, 0x09, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x67, 0x73, 0x5f, 0x6b, 0x65,
	0x65, 0x70, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x67, 0x73, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d,
	0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x67, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6e, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x67, 0x73, 0x5f, 0x6f, 0x66, 0x66, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x67, 0x73, 0x5f, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x10, 0x04,
	0x12, 0x10, 0x0a, 0x0c, 0x67, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65,
	0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x67, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10,
	0x06, 0x2a, 0x40, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x11, 0x0a,
	0x0d, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x02, 0x2a, 0x5e, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x0f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x65, 0x70, 0x69,
	0x63, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x65,
	0x6e, 0x64, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x65, 0x65,
	0x70, 0x10, 0x04, 0x2a, 0x30, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x10, 0x01, 0x2a, 0x39, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x6c, 0x66,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x65, 0x6e, 0x65, 0x6d, 0x79,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x6c, 0x6c, 0x10, 0x02,
	0x2a, 0x30, 0x0a, 0x08, 0x42, 0x75, 0x66, 0x66, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x11, 0x0a, 0x0d,
	0x62, 0x75, 0x66, 0x66, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x10, 0x01, 0x2a, 0x30, 0x0a, 0x09, 0x42, 0x75, 0x66, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x10, 0x01, 0x2a, 0xf4, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x66, 0x66, 0x45, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x10, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x61, 0x64, 0x64, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x62, 0x75, 0x66,
	0x66, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x62, 0x75, 0x66, 0x66, 0x5f,
	0x61, 0x64, 0x64, 0x5f, 0x68, 0x75, 0x72, 0x74, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x62, 0x75,
	0x66, 0x66, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x68, 0x75, 0x72, 0x74, 0x10, 0x04, 0x12, 0x15, 0x0a,
	0x11, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x5f, 0x65, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x61, 0x64, 0x64,
	0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x62, 0x75, 0x66,
	0x66, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x10, 0x07, 0x12, 0x0f,
	0x0a, 0x0b, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x76, 0x65, 0x10, 0x08, 0x12,
	0x14, 0x0a, 0x10, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x64, 0x65, 0x66, 0x65,
	0x6e, 0x73, 0x65, 0x10, 0x09, 0x12, 0x14, 0x0a, 0x10, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x73, 0x75,
	0x62, 0x5f, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x10, 0x0a, 0x2a, 0x2d, 0x0a, 0x08, 0x42,
	0x75, 0x66, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x62, 0x75, 0x66, 0x66, 0x5f,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x62, 0x75, 0x66, 0x66,
	0x5f, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x10, 0x01, 0x2a, 0x33, 0x0a, 0x0a, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x2a,
	0x98, 0x01, 0x0a, 0x0e, 0x44, 0x69, 0x63, 0x65, 0x46, 0x61, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x10, 0x64, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x64, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x64,
	0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x32, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x64, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x33, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x64, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x34, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x64, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x35, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x64, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x36, 0x10, 0x06, 0x2a, 0x50, 0x0a, 0x0b, 0x44, 0x69,
	0x63, 0x65, 0x46, 0x61, 0x63, 0x65, 0x50, 0x69, 0x63, 0x12, 0x11, 0x0a, 0x0d, 0x64, 0x69, 0x63,
	0x65, 0x5f, 0x70, 0x69, 0x63, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x64, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x5f, 0x41, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x64, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x5f, 0x42, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x64, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x5f, 0x43, 0x10, 0x03, 0x2a, 0x84, 0x01, 0x0a,
	0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07,
	0x6f, 0x6b, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x6f, 0x6b, 0x5f,
	0x73, 0x6b, 0x69, 0x70, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x6f, 0x6b, 0x5f, 0x6f, 0x75, 0x74,
	0x5f, 0x63, 0x61, 0x72, 0x64, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x6f, 0x6b, 0x5f, 0x73, 0x65,
	0x6c, 0x6c, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x6f, 0x6b, 0x5f,
	0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x64, 0x69, 0x63, 0x65, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x6f,
	0x6b, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x10, 0x05, 0x12, 0x13,
	0x0a, 0x0f, 0x6f, 0x6b, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x62, 0x75, 0x66,
	0x66, 0x10, 0x06, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x57, 0x61, 0x79, 0x6c, 0x6f, 0x6e, 0x31, 0x39, 0x39, 0x31, 0x2f, 0x4b, 0x69, 0x6e,
	0x67, 0x64, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData = file_common_common_proto_rawDesc
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_common_proto_rawDescData)
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 22)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_common_common_proto_goTypes = []interface{}{
	(LoginType)(0),          // 0: protocol.common.LoginType
	(ProtocolType)(0),       // 1: protocol.common.ProtocolType
	(RoomMode)(0),           // 2: protocol.common.RoomMode
	(HeroMatchState)(0),     // 3: protocol.common.HeroMatchState
	(ActorRace)(0),          // 4: protocol.common.ActorRace
	(ActorSex)(0),           // 5: protocol.common.ActorSex
	(ActorPro)(0),           // 6: protocol.common.ActorPro
	(EffectWay)(0),          // 7: protocol.common.EffectWay
	(HurtKind)(0),           // 8: protocol.common.HurtKind
	(GameStage)(0),          // 9: protocol.common.GameStage
	(CardKind)(0),           // 10: protocol.common.CardKind
	(CardLevel)(0),          // 11: protocol.common.CardLevel
	(CardState)(0),          // 12: protocol.common.CardState
	(CardObject)(0),         // 13: protocol.common.CardObject
	(BuffKind)(0),           // 14: protocol.common.BuffKind
	(BuffState)(0),          // 15: protocol.common.BuffState
	(BuffEffect)(0),         // 16: protocol.common.BuffEffect
	(BuffLife)(0),           // 17: protocol.common.BuffLife
	(SkillState)(0),         // 18: protocol.common.SkillState
	(DiceFaceNumber)(0),     // 19: protocol.common.DiceFaceNumber
	(DiceFacePic)(0),        // 20: protocol.common.DiceFacePic
	(OperateKind)(0),        // 21: protocol.common.OperateKind
	(*User)(nil),            // 22: protocol.common.User
	(*Hero)(nil),            // 23: protocol.common.Hero
	(*SelectInfo)(nil),      // 24: protocol.common.SelectInfo
	(*RoomCard)(nil),        // 25: protocol.common.RoomCard
	(*RoomBuf)(nil),         // 26: protocol.common.RoomBuf
	(*RoomSkill)(nil),       // 27: protocol.common.RoomSkill
	(*DiceFace)(nil),        // 28: protocol.common.DiceFace
	(*RoomDice)(nil),        // 29: protocol.common.RoomDice
	(*RoomPlayerInfo)(nil),  // 30: protocol.common.RoomPlayerInfo
	(*OperateSeatInfo)(nil), // 31: protocol.common.OperateSeatInfo
	(*OperateInfo)(nil),     // 32: protocol.common.OperateInfo
	(*OperateRecord)(nil),   // 33: protocol.common.OperateRecord
	(*RewardBall)(nil),      // 34: protocol.common.RewardBall
	(*RoomInfo)(nil),        // 35: protocol.common.RoomInfo
}
var file_common_common_proto_depIdxs = []int32{
	3,  // 0: protocol.common.Hero.state:type_name -> protocol.common.HeroMatchState
	12, // 1: protocol.common.RoomCard.state:type_name -> protocol.common.CardState
	15, // 2: protocol.common.RoomBuf.state:type_name -> protocol.common.BuffState
	18, // 3: protocol.common.RoomSkill.state:type_name -> protocol.common.SkillState
	19, // 4: protocol.common.DiceFace.num:type_name -> protocol.common.DiceFaceNumber
	20, // 5: protocol.common.DiceFace.pic:type_name -> protocol.common.DiceFacePic
	28, // 6: protocol.common.RoomDice.df:type_name -> protocol.common.DiceFace
	25, // 7: protocol.common.RoomPlayerInfo.left_cards:type_name -> protocol.common.RoomCard
	25, // 8: protocol.common.RoomPlayerInfo.hand_cards:type_name -> protocol.common.RoomCard
	25, // 9: protocol.common.RoomPlayerInfo.dis_cards:type_name -> protocol.common.RoomCard
	26, // 10: protocol.common.RoomPlayerInfo.buffs:type_name -> protocol.common.RoomBuf
	27, // 11: protocol.common.RoomPlayerInfo.skills:type_name -> protocol.common.RoomSkill
	19, // 12: protocol.common.RoomPlayerInfo.dices:type_name -> protocol.common.DiceFaceNumber
	9,  // 13: protocol.common.OperateSeatInfo.stage:type_name -> protocol.common.GameStage
	31, // 14: protocol.common.OperateInfo.seat_info:type_name -> protocol.common.OperateSeatInfo
	32, // 15: protocol.common.OperateRecord.info:type_name -> protocol.common.OperateInfo
	21, // 16: protocol.common.OperateRecord.kind:type_name -> protocol.common.OperateKind
	25, // 17: protocol.common.OperateRecord.card:type_name -> protocol.common.RoomCard
	27, // 18: protocol.common.OperateRecord.skill:type_name -> protocol.common.RoomSkill
	26, // 19: protocol.common.OperateRecord.buff:type_name -> protocol.common.RoomBuf
	29, // 20: protocol.common.OperateRecord.dice:type_name -> protocol.common.RoomDice
	2,  // 21: protocol.common.RoomInfo.mode:type_name -> protocol.common.RoomMode
	30, // 22: protocol.common.RoomInfo.players:type_name -> protocol.common.RoomPlayerInfo
	33, // 23: protocol.common.RoomInfo.record:type_name -> protocol.common.OperateRecord
	34, // 24: protocol.common.RoomInfo.ball:type_name -> protocol.common.RewardBall
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceFace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomDice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateSeatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardBall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_common_proto_rawDesc,
			NumEnums:      22,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_rawDesc = nil
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
