// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: Protocol/gate/gate.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "protocol/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *common.User        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Protocol common.ProtocolType `protobuf:"varint,2,opt,name=protocol,proto3,enum=protocol.common.ProtocolType" json:"protocol,omitempty"`
}

func (x *GateInfoRequest) Reset() {
	*x = GateInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_gate_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateInfoRequest) ProtoMessage() {}

func (x *GateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_gate_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateInfoRequest.ProtoReflect.Descriptor instead.
func (*GateInfoRequest) Descriptor() ([]byte, []int) {
	return file_Protocol_gate_gate_proto_rawDescGZIP(), []int{0}
}

func (x *GateInfoRequest) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GateInfoRequest) GetProtocol() common.ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return common.ProtocolType(0)
}

type GateInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`           // 用户本次连接加密key
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // location 本节点 ip:port
}

func (x *GateInfoReply) Reset() {
	*x = GateInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_gate_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateInfoReply) ProtoMessage() {}

func (x *GateInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_gate_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateInfoReply.ProtoReflect.Descriptor instead.
func (*GateInfoReply) Descriptor() ([]byte, []int) {
	return file_Protocol_gate_gate_proto_rawDescGZIP(), []int{1}
}

func (x *GateInfoReply) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GateInfoReply) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg   []byte         `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Users []*common.User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_gate_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_gate_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_Protocol_gate_gate_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *BroadcastRequest) GetUsers() []*common.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BroadcastReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successes []*common.User `protobuf:"bytes,1,rep,name=successes,proto3" json:"successes,omitempty"`
	Failures  []*common.User `protobuf:"bytes,2,rep,name=failures,proto3" json:"failures,omitempty"`
}

func (x *BroadcastReply) Reset() {
	*x = BroadcastReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protocol_gate_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReply) ProtoMessage() {}

func (x *BroadcastReply) ProtoReflect() protoreflect.Message {
	mi := &file_Protocol_gate_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReply.ProtoReflect.Descriptor instead.
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return file_Protocol_gate_gate_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastReply) GetSuccesses() []*common.User {
	if x != nil {
		return x.Successes
	}
	return nil
}

func (x *BroadcastReply) GetFailures() []*common.User {
	if x != nil {
		return x.Failures
	}
	return nil
}

var File_Protocol_gate_gate_proto protoreflect.FileDescriptor

var file_Protocol_gate_gate_proto_rawDesc = []byte{
	0x0a, 0x18, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f,
	0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x1a, 0x1c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0f, 0x47, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x3d, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x51, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x78, 0x0a, 0x0e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x09,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x32, 0x9d, 0x01, 0x0a,
	0x04, 0x47, 0x61, 0x74, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4b, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x0f, 0x5a, 0x0d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Protocol_gate_gate_proto_rawDescOnce sync.Once
	file_Protocol_gate_gate_proto_rawDescData = file_Protocol_gate_gate_proto_rawDesc
)

func file_Protocol_gate_gate_proto_rawDescGZIP() []byte {
	file_Protocol_gate_gate_proto_rawDescOnce.Do(func() {
		file_Protocol_gate_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protocol_gate_gate_proto_rawDescData)
	})
	return file_Protocol_gate_gate_proto_rawDescData
}

var file_Protocol_gate_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Protocol_gate_gate_proto_goTypes = []interface{}{
	(*GateInfoRequest)(nil),  // 0: protocol.gate.GateInfoRequest
	(*GateInfoReply)(nil),    // 1: protocol.gate.GateInfoReply
	(*BroadcastRequest)(nil), // 2: protocol.gate.BroadcastRequest
	(*BroadcastReply)(nil),   // 3: protocol.gate.BroadcastReply
	(*common.User)(nil),      // 4: protocol.common.User
	(common.ProtocolType)(0), // 5: protocol.common.ProtocolType
}
var file_Protocol_gate_gate_proto_depIdxs = []int32{
	4, // 0: protocol.gate.GateInfoRequest.user:type_name -> protocol.common.User
	5, // 1: protocol.gate.GateInfoRequest.protocol:type_name -> protocol.common.ProtocolType
	4, // 2: protocol.gate.BroadcastRequest.users:type_name -> protocol.common.User
	4, // 3: protocol.gate.BroadcastReply.successes:type_name -> protocol.common.User
	4, // 4: protocol.gate.BroadcastReply.failures:type_name -> protocol.common.User
	0, // 5: protocol.gate.Gate.GateInfo:input_type -> protocol.gate.GateInfoRequest
	2, // 6: protocol.gate.Gate.Broadcast:input_type -> protocol.gate.BroadcastRequest
	1, // 7: protocol.gate.Gate.GateInfo:output_type -> protocol.gate.GateInfoReply
	3, // 8: protocol.gate.Gate.Broadcast:output_type -> protocol.gate.BroadcastReply
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Protocol_gate_gate_proto_init() }
func file_Protocol_gate_gate_proto_init() {
	if File_Protocol_gate_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protocol_gate_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protocol_gate_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protocol_gate_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protocol_gate_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protocol_gate_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protocol_gate_gate_proto_goTypes,
		DependencyIndexes: file_Protocol_gate_gate_proto_depIdxs,
		MessageInfos:      file_Protocol_gate_gate_proto_msgTypes,
	}.Build()
	File_Protocol_gate_gate_proto = out.File
	file_Protocol_gate_gate_proto_rawDesc = nil
	file_Protocol_gate_gate_proto_goTypes = nil
	file_Protocol_gate_gate_proto_depIdxs = nil
}
